fix cilium doesn't show bpf prog name issue.
cilium/iproute2 pull request #11
Opened 2021-05-11 01:10 UTC by kenieevan

The iproute2 tools used by cilium to load bpf prog omits prog_name
  in bpf_attr union. This patch extracts prog_name from bpf elf file
  and pass it to kernel via union bpf_attr.

  for kernel <= 4.14, there is no prog_name in bpf_attr union so this
  patch is wrapped with PROG_NAME compile option.

  To note for this patch to work, start cilium-agent wth --bpf-compile-debug=true
  so that bpf elf symbol table is kept.

Signed-off-by: jianmingfan <jianmingfan@tencent.com>

2021-05-14 15:38 UTC, pchaigno requested changes
Thanks for tackling this! :rocket: 

> To note for this patch to work, start cilium-agent wth --bpf-compile-debug=true so that bpf elf symbol table is kept.

```
cilium$ git grep bpf-compile-debug
Documentation/operations/upgrade.rst:* ``bpf-compile-debug``: This option does not have any effect since 1.10
pkg/option/config.go:   BPFCompileDebugName = "bpf-compile-debug"
```
Did you mean something else?

2021-05-14 15:38 UTC, pchaigno commented on configure
> +}
That won't work for Cilium. We ship a single Docker image regardless of the kernel version it was compiled on, or the kernel version it will run on. So we need a `tc` binary that works for all kernel versions.

2021-05-17 01:38 UTC, kenieevan commented on configure
> +}
hi, paul
  Thanks for review this. 

For the first question,  bpf-compile-debug is used in version 1.9 to  enable -mattr=dwarfris in bpf compile so that  symbols are kept.  Seems this name is changed in recent version and i will figure it out.

For the second question,  
as cilium docker image is shipped with binary tc,  i will remove the PROG_NAME compile option from the patch.
The tc binary will work on all kernel version as changes  to uapi union bpf_attr are compatible across all kernel versions.

i will submit a new pull request later.

thanks.

2021-05-17 01:53 UTC, kenieevan commented on configure
> +}
hi, paul

as to the first question,  in recent version, bpf symbols are kept by default. so bpf-compile-debug is no longer needed,
I will fix the comments in the patch. 

thanks

>>
 datapath: always generate BTF debug information

    Enable by default the generation of the debug symbols for the BPF
    program.

    The --bpf-compile-debug option does not have any effect anymore and will
    be deprecated in version 1.11.

    Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>

>>

2021-05-17 02:43 UTC, closed without merging